### ISSUE TITLE
Remove the advertising modules and dependencies

### ISSUE THREAD

**Issue by gdongca** [gdongca/OneTap_MITBBS#7]

**Comment by sy-github** [comment]
Removed AdHelper from the main project. I have problem with testing in real phone and simulator, so it is not tested but compiled. Please help test.

**Comment by WhistMo** [comment]
Hello All,

Just back from holiday. Sorry for the late.

I am new to windows phone program. I have install Visual Studio 2015, But I
still can't open the project. Is it some quick guide to setup the
environment. Many thanks.

Sincerely,
Xingwei Mo

2016-02-16 16:08 GMT-08:00 sy-github notifications@github.com:

**Comment by WhistMo** [comment]
Hi all,

Finally finished setup up the environment including the debug phone. And I
found that some bugs had been fixed. Is there anything that I can do? Many
thanks.

Sincerely,
Xingwei mo

**Comment by gdongca** [comment]
Hi. Thanks people for the works. If you have fixed some bug listed in the
issue list, please update the issue. Thanks!

And Xingwei are you sure those bugs have been fixed? Did you test all the
cases?

Thanks,

**Comment by WhistMo** [comment]
Hi,

Most of the problems are not fixed yet.

As I don't have much experience on open source software development. I am
not very clear what to do next. Take the broken login in for example:

Previous the login url is: /mobile/mlogin.php . And I think it has changed
to /mwap/login.php
But there are some other way to login in: /iphone_new/service_new.php
and /new_index/mitbbs_login.php

There are many ways to fix to login in problem If I keep in using the
mobile mode, the problem is I don't know how to load all the BoardGroup,
before it is using /mobile/mbbssec.php  . But I can't find it in mobile
mobile. But it can be easily found in other mode.

What I mean some of problems had dependency with other problems, they are
not so independent.

Any suggest of how to fix those problems? Many thanks.

Sincerely,
Xingwei Mo

2016-02-21 12:26 GMT-08:00 Guangyu Dong notifications@github.com:

> Hi. Thanks people for the works. If you have fixed some bug listed in the
> issue list, please update the issue. Thanks!
> 
> And Xingwei are you sure those bugs have been fixed? Did you test all the
> cases?
> 
> Thanks,
>

**Comment by gdongca** [comment]
The login problem should be quite independent. The mobile site and the
regular site actually share the same login session so you can log in via
either the mobile site or the regular site and it won't make any difference.

For the content page. My suggestion is that try to switch to the regular
site if possible. Some of the page is on mobile for historical reason, not
that it is the best choice.

If you are not sure, attack the easier one first. I would suggest to fix
the login problem first. Then you will get some idea how the whole HTML
parsing codes work.

Thanks,

Guangyu

**Comment by sy-github** [comment]
@WhistMo I suggest you tackle the login issue ASAP as this is the only major problem for the app right now. I've committed changes to remove Ad banner, please help me test it if you can. Just use the app and make sure you don't see Ad banner anywhere.

I can't test myself because my machine is old and can't have emulator, also it doesn't recognise my real phone. I am upgrading my PC so I can use emulator in a few days.

Cheers.

**Comment by sy-github** [comment]
@gdongca , @WhistMo @tinaliuu How to quote and reply your message? Please write your message in the right issue ticket. Thanks.

**Comment by WhistMo** [comment]
Hi All,

I just do some quick test, the ad doesn't show up anymore. But there is
some mirror change may need. (It still has the trial version and full
version description in the app.)

I think I have fixed the login in issue. Will submit the changes tomorrow.

Sincerely,
Xingwei Mo

2016-02-22 16:10 GMT-08:00 sy-github notifications@github.com:
